version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        dependency-type: "development"
      patch-updates:
        update-types:
          - "patch"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
